[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fund = "5nNVyzESLk4QNQh7HgxAAwFmHnN37WUz1aCttBLwFo2e"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
